#if !canImport(ObjectiveC)
import XCTest

extension RainbowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RainbowTests = [
        ("testANSI", testANSI),
        ("testCocoa", testCocoa),
        ("testConversionEdgeCases", testConversionEdgeCases),
        ("testDarkLight", testDarkLight),
        ("testHexColor", testHexColor),
        ("testHSLAColor", testHSLAColor),
        ("testHSVAColor", testHSVAColor),
        ("testNegate", testNegate),
        ("testRGBAColor", testRGBAColor),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RainbowTests.__allTests__RainbowTests),
    ]
}
#endif
